package dm.uporov.feature.item_details

import dm.uporov.item_details.ItemDetailsActivityComponentDefinition.Companion.itemDetailsActivityComponentDefinition

val itemDetailsComponentDefinition = itemDetailsActivityComponentDefinition()