package dm.uporov.feature.item_details

import dm.uporov.feature.item_details.ItemDetailsActivityComponentDefinition.Companion.itemDetailsActivityComponentDefinition

val itemDetailsComponent = itemDetailsActivityComponentDefinition()